## Key Value Pair (Dictionary)
bedroom_choices = {
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5
  }

price_choices = {
  '100000': '€100,000',
  '200000': '€200,000',
  '300000': '€300,000',
  '400000': '€400,000',
  '500000': '€500,000',
  '600000': '€600,000',
  '700000': '€700,000',
  '800000': '€800,000',
  '900000': '€900,000',
  '1000000':'€1M+',
}

state_choices = {
'Adamstown'         :'Adamstown',
'Artane'            :'Artane',
'Ashtown'           :'Ashtown',
'Athgoe'            :'Athgoe',
'Balbriggan'        :'Balbriggan',
'Baldoyle'          :'Baldoyle',
'Balgriffin'        :'Balgriffin',
'Ballinteer'        :'Ballinteer',
'Ballsbridge'       :'Ballsbridge',
'Ballyboden'        :'Ballyboden',
'Ballybrack'        :'Ballybrack',
'Ballybough'        :'Ballybough',
'Ballyboughal'      :'Ballyboughal',
'Ballyfermot'       :'Ballyfermot',
'Ballygall'         :'Ballygall',
'Ballymount'        :'Ballymount',
'Ballymun'          :'Ballymun',
'Ballyroan'         :'Ballyroan',
'Balrothery'        :'Balrothery',
'Bayside'           :'Bayside',
'Beaumont'          :'Beaumont',
'Belfield'          :'Belfield',
'Blackrock'         :'Blackrock',
'Blanchardstown'    :'Blanchardstown',
'Bluebell'          :'Bluebell',
'Bohernabreena'     :'Bohernabreena',
'Booterstown'       :'Booterstown',
'Brittas'           :'Brittas',
'Broadstone'        :'Broadstone',
'Cabinteely'        :'Cabinteely',
'Cabra'             :'Cabra',
'Carrickmines'      :'Carrickmines',
'Castleknock'       :'Castleknock',
'Chapelizod'        :'Chapelizod',
'Cherrywood'        :'Cherrywood',
'Cherry Orchard'    :'Cherry Orchard',
'Churchtown'        :'Churchtown',
'Citywest'          :'Citywest',
'Clondalkin'        :'Clondalkin',
'Clongriffin'       :'Clongriffin',
'Clonsilla'         :'Clonsilla',
'Clonskeagh'        :'Clonskeagh',
'Clontarf'          :'Clontarf',
'Clonturk'          :'Clonturk',
'Coolmine'          :'Coolmine',
'Coolock'           :'Coolock',
'Corduff'           :'Corduff',
'Cornelscourt'      :'Cornelscourt',
'Crumlin'           :'Crumlin',
'Dalkey'            :'Dalkey',
'Damastown'         :'Damastown',
'Darndale'          :'Darndale',
'Dartry'            :'Dartry',
'Deansgrange'       :'Deansgrange',
'Dollymount'        :'Dollymount',
'Dolphin\'s Barn'    :'Dolphin\'s Barn',
'Donabate'          :'Donabate',
'Donaghmede'        :'Donaghmede',
'Donnybrook'        :'Donnybrook',
'Donnycarney'       :'Donnycarney',
'Drimnagh'          :'Drimnagh',
'Drumcondra'        :'Drumcondra',
'Dún Laoghaire'     :'Dún Laoghaire',
'Dundrum'           :'Dundrum',
'East Wall'         :'East Wall',
'Edmondstown'       :'Edmondstown',
'Fairview'          :'Fairview',
'Finglas'           :'Finglas',
'Firhouse'          :'Firhouse',
'Foxrock'           :'Foxrock',
'Garristown'        :'Garristown',
'Glasnevin'         :'Glasnevin',
'Glasthule'         :'Glasthule',
'Glencullen'        :'Glencullen',
'Glenageary'        :'Glenageary',
'Goatstown'         :'Goatstown',
'Grangegorman'      :'Grangegorman',
'Harold\'s Cross'    :'Harold\'s Cross',
'Hollystown'        :'Hollystown',
'Howth'             :'Howth',
'Inchicore'         :'Inchicore',
'Irishtown'         :'Irishtown',
'Islandbridge'      :'Islandbridge',
'Jobstown'          :'Jobstown',
'Kill O\' The Grange':'Kill O\' The Grange',
'Kilbarrack'        :'Kilbarrack',
'Killester'         :'Killester',
'Killiney'          :'Killiney',
'Kilmacud'          :'Kilmacud',
'Kilmainham'        :'Kilmainham',
'Kilnamanagh'       :'Kilnamanagh',
'Kilternan'         :'Kilternan',
'Kimmage'           :'Kimmage',
'Kinsealy'          :'Kinsealy',
'Knocklyon'         :'Knocklyon',
'Leopardstown'      :'Leopardstown',
'The Liberties'     :'The Liberties',
'Loughlinstown'     :'Loughlinstown',
'Loughshinny'       :'Loughshinny',
'Lucan'             :'Lucan',
'Lusk'              :'Lusk',
'Malahide'          :'Malahide',
'Marino'            :'Marino',
'Merrion'           :'Merrion',
'Milltown'          :'Milltown',
'Monkstown'         :'Monkstown',
'Mount Merrion'     :'Mount Merrion',
'Mulhuddart'        :'Mulhuddart',
'Newcastle'         :'Newcastle',
'Naul'              :'Naul',
'North Strand'      :'North Strand',
'North Wall'        :'North Wall',
'Oldbawn'           :'Oldbawn',
'Oldtown'           :'Oldtown',
'Ongar'             :'Ongar',
'Palmerstown'       :'Palmerstown',
'Perrystown'        :'Perrystown',
'Phibsborough'      :'Phibsborough',
'Poppintree'        :'Poppintree',
'Portmarnock'       :'Portmarnock',
'Portobello'        :'Portobello',
'Portrane'          :'Portrane',
'Raheny'            :'Raheny',
'Ranelagh'          :'Ranelagh',
'Rathcoole'         :'Rathcoole',
'Rathfarnham'       :'Rathfarnham',
'Rathgar'           :'Rathgar',
'Rathmichael'       :'Rathmichael',
'Rathmines'         :'Rathmines',
'Rialto'            :'Rialto',
'Ringsend'          :'Ringsend',
'Rolestown'         :'Rolestown',
'Rush'              :'Rush',
'Saggart'           :'Saggart',
'Sallynoggin'       :'Sallynoggin',
'Sandycove'         :'Sandycove',
'Sandyford'         :'Sandyford',
'Sandymount'        :'Sandymount',
'Santry'            :'Santry',
'Shankill'          :'Shankill',
'Skerries'          :'Skerries',
'Smithfield'        :'Smithfield',
'Stepaside'         :'Stepaside',
'Stillorgan'        :'Stillorgan',
'Stoneybatter'      :'Stoneybatter',
'Sutton'            :'Sutton',
'Swords'            :'Swords',
'Tallaght'          :'Tallaght',
'Templeogue'        :'Templeogue',
'Terenure'          :'Terenure',
'The Coombe'        :'The Coombe',
'Ticknock'          :'Ticknock',
'Tyrrelstown'       :'Tyrrelstown',
'Walkinstown'       :'Walkinstown',
'Whitechurch'       :'Whitechurch',
'Whitehall'         :'Whitehall',
'Windy Arbour'      :'Windy Arbour'
}